<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- 後で Unity からも参照するため netstandard2.1 + C# 9 に固定する -->
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Terrace.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MagicOnion.Abstractions" Version="7.10.2" />
    <PackageReference Include="MessagePack" Version="3.1.8" />
  </ItemGroup>

</Project>
